/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface User {
  id: string;
  username: string;
}

export interface UserAuth {
  password: string;
  salt: string;
  userId: string | null;
}

export interface DB {
  user: User;
  userAuth: UserAuth;
}
