/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface User {
  email: string;
  id: Generated<number | null>;
}

export interface UserAuth {
  password: string | null;
  userId: Generated<number | null>;
}

export interface DB {
  user: User;
  userAuth: UserAuth;
}
